### ISSUE TITLE
broken logic for banned user

### ISSUE THREAD

**Issue by TitanVJ** [CSSS/wall_e_models#5]
https://github.com/CSSS/wall_e_models/blob/df85e403a8f1cadec4d688aed02ec8d014ab9f27/wall_e_models/models.py#L105

**Comment by TitanVJ** [comment]
it'll return true for previously banned user thats currently unbanned. have to check for the unban date field like in https://github.com/CSSS/wall_e_models/blob/df85e403a8f1cadec4d688aed02ec8d014ab9f27/wall_e_models/models.py#L94C75-L94C75

**Comment by modernNeo** [comment]
fair but the method isn't actually used anyways so probably just have to remove it

**Comment by TitanVJ** [comment]
> fair but the method isn't actually used anyways so probably just have to remove it

it's used in levelling cog: https://github.com/CSSS/wall_e/blob/20dbb1c0b76c3a726387a8bdc7135d88a8cf7c90/wall_e/extensions/leveling.py#L420

**Comment by modernNeo** [comment]
ah

**Comment by modernNeo** [comment]
wonder if I can switch that over to `ban_list` too 🤔

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/commit/7aa60aed38f7ca5ee2e7005de727377e44f38021
